kind: pipeline
name: kernel_build

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: setup&build
    image: ubuntu:latest
    environment:
      ftp_server:
        from_secret: ftp_server
      ftp_username:
        from_secret: ftp_username
      ftp_pwd:
        from_secret: ftp_pwd
    commands:
      - export HOME=/drone
      - ./build.sh
